trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshiftcs'
    version: '4.14.1'
    cmd: 'oc project mauriciojimenez-1-dev'
  displayName: Switch to project
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshiftcs'
    version: '4.14.1'
    cmd: 'oc new-app https://github.com/majimro/ambiente.git'
    ignoreFlag: true
  displayName: Load repo
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshiftcs'
    version: '4.14.1'
    cmd: 'oc expose service/ambiente'
    ignoreFlag: true
  displayName: Create route
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshiftcs'
    version: '4.14.1'
    cmd: 'oc start-build ambiente --follow'
    ignoreFlag: true
  displayName: Start new build
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshiftcs'
    version: '4.14.1'
    cmd: 'oc status'
